import type { Coverage } from './types';

/** Human-readable rendering of coverage.json, for review. */
export function renderCoverageReport(c: Coverage): string {
  const L: string[] = [];
  const row = (...cells: (string | number)[]) => L.push(`| ${cells.join(' | ')} |`);

  L.push(`# Coverage report`, '', `Schema ${c.schema_version}. Generated by \`npm run mtb:ingest\`.`, '');

  L.push('## Tables', '');
  row('Table', 'File', 'Records', 'Valid', 'Excluded', 'Dangling FKs', 'Fields not in schema');
  row('---', '---', '---', '---', '---', '---', '---');
  for (const [name, t] of Object.entries(c.tables)) {
    row(name, t.file_present ? 'yes' : 'absent', t.records, t.valid, t.excluded, t.dangling_fks.length, t.unknown_fields.length);
  }

  L.push('', '## Showable units', '', 'What a rider can actually select today.', '');
  L.push(`Forks (${c.showable.fork_units.length}):`);
  for (const u of c.showable.fork_units) L.push(`- ${u.display_name} \`${u.id}\``);
  L.push('', `Shocks (${c.showable.shock_units.length}):`);
  for (const u of c.showable.shock_units) L.push(`- ${u.display_name} \`${u.id}\``);

  L.push('', '## Brands', '');
  row('Brand', 'Chassis', 'Dampers', 'Air springs', 'Pressure charts', 'Setting charts', 'Fork units', 'Shock units');
  row('---', '---', '---', '---', '---', '---', '---', '---');
  for (const [b, s] of Object.entries(c.brands)) {
    row(b, s.chassis, s.dampers, s.air_springs, s.pressure_charts, s.setting_charts, s.fork_units, s.shock_units);
  }

  const a = c.adjuster_counts;
  L.push('', '## Adjuster counts', '');
  L.push(`${a.adjusters_present} adjusters present, ${a.adjusters_absent} absent (null = does not exist).`);
  L.push(`By type: ${Object.entries(a.by_type).map(([k, n]) => `${k} ${n}`).join(', ')}.`, '');
  row('Count state', 'Adjusters');
  row('---', '---');
  row('Total with count_basis (usable for clamping)', a.count_with_basis);
  row('Held back: count without count_basis', a.count_held_back);
  row('Derived from lever positions', a.count_derived_from_positions);
  row('Null, declared pending', a.count_null_pending);
  row('Null, bare (no fields_pending entry)', a.count_null_bare);
  row('Not applicable (sweep)', a.count_not_applicable);

  L.push('', '## Field-level changes made at ingest', '', 'Raw files are untouched. These are applied to the index only.', '');
  if (!c.annotations.length) L.push('None.');
  for (const x of c.annotations.filter((a) => a.kind !== 'overlay')) {
    L.push(`- **${x.kind}** \`${x.table}:${x.id}\` ${x.path}: ${JSON.stringify(x.original)} → ${JSON.stringify(x.value)}. ${x.reason}.`);
  }

  const ov = c.annotations.filter((a) => a.kind === 'overlay');
  L.push('', '## Overlay: gaps filled on top of raw', '', 'From src/mtb/data/overlay/overlay.ts. Each entry retires itself when a harvest supplies the value.', '');
  for (const basis of ['correction', 'research', 'estimate'] as const) {
    const xs = ov.filter((a) => a.basis === basis);
    L.push(`### ${basis} (${xs.length})`, '');
    for (const x of xs) {
      const what = x.path === '(record)' ? 'new record' : `${x.path} → ${JSON.stringify(x.value)}`;
      L.push(`- \`${x.table}:${x.id}\` ${what}. ${x.reason}`);
    }
    L.push('');
  }

  L.push('', '## Exclusions', '');
  if (!c.exclusions.length) L.push('None. Every record validated and every foreign key resolved.');
  for (const e of c.exclusions) L.push(`- \`${e.table}:${e.id}\`: ${e.reasons.join('; ')}`);

  L.push('', '## Data flags', '');
  const byCode = new Map<string, typeof c.flags>();
  for (const f of c.flags) byCode.set(f.code, [...(byCode.get(f.code) ?? []), f]);
  for (const [code, fs] of byCode) {
    L.push(`### ${code} (${fs.length}, ${fs[0].severity})`, '');
    for (const f of fs) L.push(`- \`${f.table}:${f.id}\`: ${f.message}`);
    L.push('');
  }

  L.push('## Null fields by table', '', 'Pending means declared in `fields_pending`. Bare means null with no declaration. Absent means the key is missing, usually a field added in v0.3.', '');
  for (const [name, t] of Object.entries(c.tables)) {
    const gaps = Object.entries(t.fields).filter(([, s]) => s.null_bare || s.null_pending || s.absent);
    if (!t.valid || !gaps.length) continue;
    L.push(`### ${name} (${t.valid} valid)`, '');
    row('Field', 'Populated', 'Pending', 'Bare null', 'Absent');
    row('---', '---', '---', '---', '---');
    for (const [f, s] of gaps) row(f, s.populated, s.null_pending, s.null_bare, s.absent);
    L.push('');
  }

  L.push('## Readiness gates', '');
  row('Feature', 'Meaningful after', 'Ready', 'Evidence');
  row('---', '---', '---', '---');
  for (const g of c.readiness) row(g.feature, g.meaningful_after, g.ready ? 'yes' : 'no', g.evidence);
  L.push('');
  return L.join('\n');
}
