import indexJson from './build/index.json';
import coverageJson from './build/coverage.json';
import type { Coverage, DataIndex } from './ingest/types';

/**
 * The ingested dataset, generated by `npm run mtb:ingest` (chained into predev, prebuild and pretest).
 * Validated at build time; read only at runtime.
 */
export const INDEX = indexJson as unknown as DataIndex;
export const COVERAGE = coverageJson as unknown as Coverage;
